name: BorhanAdmin
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^3.0.0
  app_settings: ^4.0.0
  intl: ^0.15.8
  http: ^0.12.0+2
  image_picker: ^0.6.6+1
  firebase_core: ^0.4.0+9
  firebase_storage: ^3.1.5
  firebase_database:
  toast: ^0.1.5
  location: ^3.0.0
  video_player:
  flutter_email_sender: ^3.0.1
  firebase_auth: ^0.16.0

  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.2.0
  google_maps_flutter: ^0.5.28+1
  cached_network_image: ^2.2.0+1
  shared_preferences: ^0.5.7+3
  connectivity: ^0.4.8+6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.5
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#191919"
  adaptive_icon_foreground: "assets/images/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/demo/borhan.mp4
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
    - family: Anton
      fonts:
        - asset: assets/fonts/Anton-Regular.ttf
